
# https://fasttext.cc/docs/en/language-identification.html
# Language Code =>
#   Language Family
#   ISO language name
#   Native name (endonym)
#   ISO 639-1
#   ISO 639-2/T
#   ISO 639-2/B
#   ISO 639-3
FASTTEXT_LANGUAGES = {
    'af': ('Indo-European', 'Afrikaans', 'Afrikaans', 'af', 'afr', 'afr', 'afr'),
    'sq': ('Indo-European', 'Albanian', 'Shqip', 'sq', 'sqi', 'alb', 'sqi'),
    'am': ('Afro-Asiatic', 'Amharic', 'አማርኛ', 'am', 'amh', 'amh', 'amh'),
    'ar': ('Afro-Asiatic', 'Arabic', 'العربية', 'ar', 'ara', 'ara', 'ara'),
    'an': ('Indo-European', 'Aragonese', 'aragonés', 'an', 'arg', 'arg', 'arg'),
    'hy': ('Indo-European', 'Armenian', 'Հայերեն', 'hy', 'hye', 'arm', 'hye'),
    'as': ('Indo-European', 'Assamese', 'অসমীয়া', 'as', 'asm', 'asm', 'asm'),
    'av': ('Northeast Caucasian', 'Avaric', 'авар мацӀ, магӀарул мацӀ', 'av', 'ava', 'ava', 'ava'),
    'az': ('Turkic', 'Azerbaijani', 'azərbaycan dili', 'az', 'aze', 'aze', 'aze'),
    'ba': ('Turkic', 'Bashkir', 'башҡорт теле', 'ba', 'bak', 'bak', 'bak'),
    'eu': ('Language isolate', 'Basque', 'euskara, euskera', 'eu', 'eus', 'baq', 'eus'),
    'be': ('Indo-European', 'Belarusian', 'беларуская мова', 'be', 'bel', 'bel', 'bel'),
    'bn': ('Indo-European', 'Bengali', 'বাংলা', 'bn', 'ben', 'ben', 'ben'),
    'bh': ('Indo-European', 'Bihari', 'भोजपुरी', 'bh', 'bih', 'bih', ''),
    'bs': ('Indo-European', 'Bosnian', 'bosanski jezik', 'bs', 'bos', 'bos', 'bos'),
    'br': ('Indo-European', 'Breton', 'brezhoneg', 'br', 'bre', 'bre', 'bre'),
    'bg': ('Indo-European', 'Bulgarian', 'български език', 'bg', 'bul', 'bul', 'bul'),
    'my': ('Sino-Tibetan', 'Burmese', 'ဗမာစာ', 'my', 'mya', 'bur', 'mya'),
    'ca': ('Indo-European', 'Catalan', 'català, valencià', 'ca', 'cat', 'cat', 'cat'),
    'ce': ('Northeast Caucasian', 'Chechen', 'нохчийн мотт', 'ce', 'che', 'che', 'che'),
    'zh': ('Sino-Tibetan', 'Chinese', '中文 (Zhōngwén), 汉语, 漢語', 'zh', 'zho', 'chi', 'zho'),
    'cv': ('Turkic', 'Chuvash', 'чӑваш чӗлхи', 'cv', 'chv', 'chv', 'chv'),
    'kw': ('Indo-European', 'Cornish', 'Kernewek', 'kw', 'cor', 'cor', 'cor'),
    'co': ('Indo-European', 'Corsican', 'corsu, lingua corsa', 'co', 'cos', 'cos', 'cos'),
    'hr': ('Indo-European', 'Croatian', 'hrvatski jezik', 'hr', 'hrv', 'hrv', 'hrv'),
    'cs': ('Indo-European', 'Czech', 'čeština, český jazyk', 'cs', 'ces', 'cze', 'ces'),
    'da': ('Indo-European', 'Danish', 'dansk', 'da', 'dan', 'dan', 'dan'),
    'dv': ('Indo-European', 'Divehi', 'ދިވެހި', 'dv', 'div', 'div', 'div'),
    'nl': ('Indo-European', 'Dutch', 'Nederlands, Vlaams', 'nl', 'nld', 'dut', 'nld'),
    'en': ('Indo-European', 'English', 'English', 'en', 'eng', 'eng', 'eng'),
    'eo': ('Constructed', 'Esperanto', 'Esperanto', 'eo', 'epo', 'epo', 'epo'),
    'et': ('Uralic', 'Estonian', 'eesti, eesti keel', 'et', 'est', 'est', 'est'),
    'fi': ('Uralic', 'Finnish', 'suomi, suomen kieli', 'fi', 'fin', 'fin', 'fin'),
    'fr': ('Indo-European', 'French', 'français, langue française', 'fr', 'fra', 'fre', 'fra'),
    'gl': ('Indo-European', 'Galician', 'Galego', 'gl', 'glg', 'glg', 'glg'),
    'ka': ('Kartvelian', 'Georgian', 'ქართული', 'ka', 'kat', 'geo', 'kat'),
    'de': ('Indo-European', 'German', 'Deutsch', 'de', 'deu', 'ger', 'deu'),
    'el': ('Indo-European', 'Greek', 'ελληνικά', 'el', 'ell', 'gre', 'ell'),
    'gn': ('Tupian', 'Guarani', 'Avañe\'ẽ', 'gn', 'grn', 'grn', 'grn'),
    'gu': ('Indo-European', 'Gujarati', 'ગુજરાતી', 'gu', 'guj', 'guj', 'guj'),
    'ht': ('Creole', 'Haitian', 'Kreyòl ayisyen', 'ht', 'hat', 'hat', 'hat'),
    'he': ('Afro-Asiatic', 'Hebrew', 'עברית', 'he', 'heb', 'heb', 'heb'),
    'hi': ('Indo-European', 'Hindi', 'हिन्दी, हिंदी', 'hi', 'hin', 'hin', 'hin'),
    'hu': ('Uralic', 'Hungarian', 'magyar', 'hu', 'hun', 'hun', 'hun'),
    'ia': ('Constructed', 'Interlingua', 'Interlingua', 'ia', 'ina', 'ina', 'ina'),
    'id': ('Austronesian', 'Indonesian', 'Bahasa Indonesia', 'id', 'ind', 'ind', 'ind'),
    'ie': ('Constructed', 'Interlingue', 'Interlingue', 'ie', 'ile', 'ile', 'ile'),
    'ga': ('Indo-European', 'Irish', 'Gaeilge', 'ga', 'gle', 'gle', 'gle'),
    'io': ('Constructed', 'Ido', 'Ido', 'io', 'ido', 'ido', 'ido'),
    'is': ('Indo-European', 'Icelandic', 'Íslenska', 'is', 'isl', 'ice', 'isl'),
    'it': ('Indo-European', 'Italian', 'Italiano', 'it', 'ita', 'ita', 'ita'),
    'ja': ('Japonic', 'Japanese', '日本語 (にほんご)', 'ja', 'jpn', 'jpn', 'jpn'),
    'jv': ('Austronesian', 'Javanese', 'ꦧꦱꦗꦮ, Basa Jawa', 'jv', 'jav', 'jav', 'jav'),
    'kn': ('Dravidian', 'Kannada', 'ಕನ್ನಡ', 'kn', 'kan', 'kan', 'kan'),
    'kk': ('Turkic', 'Kazakh', 'қазақ тілі', 'kk', 'kaz', 'kaz', 'kaz'),
    'km': ('Austroasiatic', 'Central Khmer', 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ', 'km', 'khm', 'khm', 'khm'),