name: Push to Main

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/main.yml"
      - "Dockerfile"
      - "src/**"
      - "requirements.txt"
      - "setup.py"

jobs:
  main